# .readthedocs.yaml
# Read the Docs configuration file
# https://docs.readthedocs.io/stable/config-file/v2.html

# Required
version: 2

# Set OS, Python version, and other tools
build:
  os: ubuntu-lts-latest
  tools:
    python: latest

# Install local thevenin package
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Location of sphinx configuration file
sphinx:
  configuration: docs/source/conf.py
