[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "thevenin"
dynamic = ["version"]
description = "Packaged Thevenin equivalent circuit model."
requires-python = ">=3.8,<3.12"
authors = [
    {name = "Corey R. Randall", email = "corey.randall@nrel.gov"},
]
maintainers = [
    {name = "Corey R. Randall", email = "corey.randall@nrel.gov"},
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "numpy",
    "scipy",
    "scikits.odes",
    "matplotlib",
    "ruamel.yaml",
]

[tool.setuptools.dynamic]
version = {attr = "thevenin.__version__"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
thevenin = ["templates/*.yaml", "docs/*"]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "genbadge[all]",
    "codespell",
    "sphinx",
    "sphinx-autoapi",
    "sphinx-design",
    "sphinx-favicon",
    "sphinx-copybutton",
    "myst-nb",
    "pydata-sphinx-theme",
]
