name: build-and-test

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - 'README*'
      - 'LICENSE*'
      - 'images/*'

  pull_request:
    branches: [main]
    paths-ignore:
      - '*.md'
      - 'README*'
      - 'LICENSE*'
      - 'images/*'

jobs:
  lint:
    name: (Lint ${{ matrix.python-version }}, ${{ matrix.os }})

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.10']

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Spell check
        run: |
          pip install codespell
          codespell --config .github/linters/.codespellrc
      - name: Code format
        run: |
          pip install flake8
          flake8 --config .github/linters/.flake8 src

  win-lin-tests:
    name: (Test ${{ matrix.python-version }}, ${{ matrix.os }})

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        python-version: ['3.8', '3.11']

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: 'rovi'
          python-version: ${{ matrix.python-version }}
          miniconda-version: 'latest'
          use-only-tar-bz2: true
          auto-update-conda: true
          auto-activate-base: true
      - name: Conda dependencies
        run: conda install scikits.odes -c conda-forge
      - name: Pip dependencies
        run: pip install .
      - name: List packages
        run: conda list
      - name: Pytest
        run: |
          pip install pytest
          pytest

  mac-tests:
    name: (Test ${{ matrix.python-version }}, ${{ matrix.os }})

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['macos-latest']
        python-version: ['3.8', '3.11']

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: 'rovi'
          miniconda-version: 'latest'
          use-only-tar-bz2: true
          auto-update-conda: true
          auto-activate-base: true
      - name: Make environment
        run: |
          conda info
          conda config --env --set subdir osx-64
          conda install python=${{ matrix.python-version }} scikits.odes -c conda-forge
      - name: Pip dependencies
        run: pip install .
      - name: List packages
        run: conda list
      - name: Pytest
        run: |
          pip install pytest
          pytest