name: build-and-test

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - 'README*'
      - 'LICENSE'
      - 'docs/*'
      - 'images/*'

  pull_request:
    branches: [main]
    paths-ignore:
      - '*.md'
      - 'README*'
      - 'LICENSE'
      - 'docs/*'
      - 'images/*'

jobs:
  lint:
    name: (Lint ${{ matrix.python-version }}, ${{ matrix.os }})

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.10']

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Spell check
        run: |
          pip install codespell
          codespell --config .github/linters/.codespellrc

  tests:
    name: (Test ${{ matrix.python-version }}, ${{ matrix.os }})

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest'] # ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.8', '3.11']

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: 'latest'
          use-only-tar-bz2: true
          auto-update-conda: true
          auto-activate-base: true
      - name: Make environment
        run: |
          conda create -n rovi
          conda activate rovi
      - name: Conda dependencies
        run: conda install -c conda-forge scikits.odes
      - name: Pip dependencies
        run: pip install .
      - name: List packages
        run: conda list
      - name: Pytest
        run: |
          pip install pytest
          pytest