name: build-and-test

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.txt'
      - 'README*'
      - 'CHANGELOG*'
      - 'docs/*'
      - 'images/*'
      - 'LICENSE'
      - '.github/ISSUE_TEMPLATE/*'

  pull_request:
    branches: [main]
    paths-ignore:
      - '*.md'
      - '*.txt'
      - 'README*'
      - 'CHANGELOG*'
      - 'docs/*'
      - 'images/*'
      - 'LICENSE'
      - '.github/ISSUE_TEMPLATE/*'

jobs:
  lint:
    name: (Lint ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.13']

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Spell check
        run: |
          pip install codespell
          codespell --config .github/linters/.codespellrc

      - name: Code format
        run: |
          pip install flake8
          flake8 --config .github/linters/.flake8 src
          flake8 --config .github/linters/.flake8 tests

  tests:
    name: (Test ${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-latest, windows-latest, ubuntu-latest]
        python-version: ['3.9', '3.13']

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup conda/python
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniconda-version: latest
          python-version: ${{ matrix.python-version }}
          activate-environment: rovi

      - name: Verify environment
        run: |
          conda info
          conda list

      - name: Pip dependencies
        run: pip install .

      - name: List info
        run: |
          conda info
          conda list

      - name: Pytest
        run: |
          pip install pytest
          pytest .
